# Generated by Django 4.2.9 on 2025-11-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_rename_model_productvariant_variant_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="careguide",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Care Guide",
                "verbose_name_plural": "Care Guides",
            },
        ),
        migrations.AddField(
            model_name="careguide",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="careguide",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Display Order"),
        ),
        migrations.AddField(
            model_name="careguide",
            name="title",
            field=models.CharField(
                default="General Care", max_length=255, verbose_name="Care Guide Title"
            ),
        ),
        migrations.AlterField(
            model_name="careguide",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_guides",
                to="user.productvariant",
                verbose_name="Product Variant",
            ),
        ),
        migrations.AddIndex(
            model_name="careguide",
            index=models.Index(
                fields=["variant", "is_active"], name="user_caregu_variant_c03fa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="careguide",
            index=models.Index(fields=["order"], name="user_caregu_order_442791_idx"),
        ),
    ]
